export const allMockRecords = [
    { id: 'mock-id-1', type: 'Blood Report', date: '2025-09-15', doctor: 'Dr. Priya Sharma', clinic: 'Ayu Health Center', status: 'Reviewed', findings: 'All parameters within normal range. Mild iron deficiency noted.' },
    { id: 'mock-id-2', type: 'Blood Report', date: '2025-09-12', doctor: 'Dr. Ravi Kumar', clinic: 'City General Hospital', status: 'Normal', findings: 'Complete blood count is normal. No abnormalities detected.' },
    { id: 'mock-id-3', type: 'Prescription', date: '2025-09-05', doctor: 'Dr. Priya Sharma', clinic: 'Ayu Health Center', status: 'Reviewed', findings: 'Prescribed Paracetamol for fever. Advised rest.' },
    { id: 'mock-id-4', type: 'Consultation', date: '2025-09-05', doctor: 'Dr. Priya Sharma', clinic: 'Ayu Health Center', status: 'Reviewed', findings: 'Patient reported symptoms of mild fever and fatigue. General check-up performed.' },
    { id: 'mock-id-5', type: 'Scan', date: '2025-08-21', doctor: 'Dr. Anand Gupta', clinic: 'Advanced Diagnostics', status: 'Normal', findings: 'Chest X-Ray shows clear lungs. No signs of infection.' },
    { id: 'mock-id-6', type: 'Blood Report', date: '2025-07-15', doctor: 'Dr. Ravi Kumar', clinic: 'City General Hospital', status: 'Normal', findings: 'Lipid profile is within the healthy range.' },
    { id: 'mock-id-7', type: 'Prescription', date: '2025-06-30', doctor: 'Dr. Meena Singh', clinic: 'Community Clinic', status: 'Reviewed', findings: 'Prescribed antibiotics for a minor throat infection.' },
    { id: 'mock-id-8', type: 'Consultation', date: '2025-06-30', doctor: 'Dr. Meena Singh', clinic: 'Community Clinic', status: 'Reviewed', findings: 'Patient complained of a sore throat. Examination revealed mild inflammation.' },
    { id: 'mock-id-9', type: 'Scan', date: '2025-05-10', doctor: 'Dr. Anand Gupta', clinic: 'Advanced Diagnostics', status: 'Reviewed', findings: 'MRI of the knee shows minor cartilage wear. No significant damage.' },
  ];
  
  export const allMockDoctors = [
      { id: 'doc-1', name: 'Dr. Sunita Rao', type: 'doctor', specialty: 'Cardiologist', location: 'Mumbai', rating: 4.8, distance: 2.5, phone: '+91 98765 43210', email: 'sunita.rao@ayu-raksha.hosp', address: '123 Cardiac Care, Andheri, Mumbai', about: 'Dr. Rao is a renowned cardiologist with over 15 years of experience in treating complex heart conditions. She is known for her patient-centric approach and dedication to cardiac wellness.', services: ['ECG', 'Echocardiogram', 'Angioplasty Consultation'] },
      { id: 'hos-1', name: 'Global Hospital', type: 'hospital', specialty: 'Multi-Specialty Hospital', location: 'Delhi', rating: 4.5, distance: 5.1, phone: '+91 11 4567 8901', email: 'contact@globalhosp.in', address: '45 Health Avenue, Saket, New Delhi', about: 'Global Hospital is a state-of-the-art multi-specialty facility offering comprehensive medical services with advanced technology and a team of expert doctors.', services: ['24/7 Emergency', 'ICU', 'Radiology', 'Pathology Lab'] },
      { id: 'doc-2', name: 'Dr. Anil Verma', type: 'doctor', specialty: 'General Physician', location: 'Near Me', rating: 4.6, distance: 1.2, phone: '+91 91234 56789', email: 'anil.verma@ayu-raksha.hosp', address: '15 Community Clinic, Civil Lines, Prayagraj', about: 'Dr. Verma has been serving the community for over a decade, providing expert primary care for all ages. He focuses on preventive medicine and holistic health.', services: ['General Check-up', 'Vaccinations', 'Fever Treatment'] },
      { id: 'doc-3', name: 'Dr. Meera Krishnan', type: 'doctor', specialty: 'Pediatrician', location: 'Kochi', rating: 4.9, distance: 8.3, phone: '+91 99887 76655', email: 'meera.k@ayu-raksha.hosp', address: '7 Child Wellness Center, MG Road, Kochi', about: 'Dr. Krishnan is a leading pediatrician with a passion for child health. She creates a friendly and comfortable environment for her young patients.', services: ['Newborn Care', 'Childhood Vaccinations', 'Growth Monitoring'] },
      { id: 'doc-4', name: 'Dr. Rajesh Patel', type: 'doctor', specialty: 'Dermatologist', location: 'Mumbai', rating: 4.7, distance: 3.0, phone: '+91 98765 12345', email: 'rajesh.patel@ayu-raksha.hosp', address: '22 Skin & Hair Clinic, Bandra, Mumbai', about: 'Dr. Patel specializes in both clinical and cosmetic dermatology, offering advanced treatments for a wide range of skin conditions.', services: ['Acne Treatment', 'Skin Allergy Testing', 'Laser Hair Removal'] },
      { id: 'hos-2', name: 'City Care Clinic', type: 'hospital', specialty: 'Multi-Specialty Hospital', location: 'Near Me', rating: 4.2, distance: 2.8, phone: '+91 532 234 5678', email: 'info@citycareprayagraj.in', address: '88 M.G. Marg, Prayagraj', about: 'City Care Clinic provides accessible and affordable healthcare with a focus on outpatient services and minor procedures.', services: ['OPD Consultations', 'Pharmacy', 'Minor Surgery'] },
      { id: 'doc-5', name: 'Dr. Arjun Reddy', type: 'doctor', specialty: 'Cardiologist', location: 'Delhi', rating: 4.4, distance: 12.0, phone: '+91 91122 33445', email: 'arjun.reddy@ayu-raksha.hosp', address: '9 Heartbeat Center, Karol Bagh, New Delhi', about: 'Dr. Reddy is a dynamic cardiologist known for his expertise in interventional cardiology and cardiac imaging techniques.', services: ['TMT', 'Holter Monitoring', 'Cardiac Consultation'] },
    ];
  
  export const mockAlerts = [
    {
      id: 'alert-1', type: 'High Risk', date: '2025-09-28',
      title: { English: 'Dengue Risk in Current Location', 'हिंदी': 'वर्तमान स्थान में डेंगू का खतरा', 'മലയാളം': 'നിലവിലെ സ്ഥലത്ത് ഡെങ്കിപ്പനി സാധ്യത' },
      summary: { English: 'Increased dengue mosquito activity reported in Prayagraj due to recent monsoon rains.', 'हिंदी': 'हाल ही में हुई मानसूनी बारिश के कारण प्रयागराज में डेंगू मच्छर की गतिविधियां बढ़ने की सूचना है।', 'മലയാളം': 'സമീപകാലത്തെ മൺസൂൺ മഴയെത്തുടർന്ന് പ്രയാഗ്‌രാജിൽ ഡെങ്കിപ്പനി കൊതുകുകളുടെ പ്രവർത്തനം വർദ്ധിച്ചതായി റിപ്പോർട്ട്.' },
      details: { English: 'Local health authorities have noted a spike in dengue cases. It is crucial to eliminate stagnant water sources around your home, use mosquito repellent, and wear long-sleeved clothing, especially during dawn and dusk. If you experience high fever, severe headache, or body aches, consult a doctor immediately.', 'हिंदी': 'स्थानीय स्वास्थ्य अधिकारियों ने डेंगू के मामलों में वृद्धि देखी है। अपने घर के आसपास स्थिर पानी के स्रोतों को खत्म करना, मच्छर भगाने वाली क्रीम का उपयोग करना और खासकर सुबह और शाम के समय लंबी आस्तीन वाले कपड़े पहनना महत्वपूर्ण है। यदि आपको तेज बुखार, गंभीर सिरदर्द या शरीर में दर्द का अनुभव हो तो तुरंत डॉक्टर से सलाह लें।', 'മലയാളം': 'പ്രാദേശിക ആരോഗ്യ അധികാരികൾ ഡെങ്കിപ്പനി കേസുകളിൽ വർദ്ധനവ് രേഖപ്പെടുത്തിയിട്ടുണ്ട്. നിങ്ങളുടെ വീടിന് ചുറ്റുമുള്ള കെട്ടിക്കിടക്കുന്ന വെള്ളം ഒഴിവാക്കുക, കൊതുക് விரட்டும் மருந்து ഉപയോഗിക്കുക, പുലർച്ചെയും സന്ധ്യാസമയത്തും നീണ്ട കൈകളുള്ള വസ്ത്രങ്ങൾ ധരിക്കുക. ഉയർന്ന പനി, കടുത്ത തലവേദന, അല്ലെങ്കിൽ ശരീരവേദന അനുഭവപ്പെട്ടാൽ ഉടൻ ഡോക്ടറെ സമീപിക്കുക.' },
    },
    {
      id: 'alert-2', type: 'Guidance', date: '2025-09-25',
      title: { English: 'Post-Viral Fatigue Management', 'हिंदी': 'वायरल के बाद की थकान का प्रबंधन', 'മലയാളം': 'വൈറൽ അണുബാധയ്ക്ക് ശേഷമുള്ള ക്ഷീണം കൈകാര്യം ചെയ്യൽ' },
      summary: { English: 'Based on your recent consultation for fever, here are tips to manage post-viral fatigue.', 'हिंदी': 'बुखार के लिए आपकी हालिया परामर्श के आधार पर, वायरल के बाद की थकान को प्रबंधित करने के लिए यहां कुछ सुझाव दिए गए हैं।', 'മലയാളം': 'പനിക്കുള്ള നിങ്ങളുടെ സമീപകാല കൺസൾട്ടേഷന്റെ അടിസ്ഥാനത്തിൽ, വൈറൽ അണുബാധയ്ക്ക് ശേഷമുള്ള ക്ഷീണം കൈകാര്യം ചെയ്യുന്നതിനുള്ള നുറുങ്ങുകൾ ഇതാ.' },
      details: { English: 'It is common to feel tired after a viral infection. Ensure you get adequate rest, stay hydrated by drinking plenty of fluids, and eat nutritious meals. Gradually reintroduce light physical activity like walking. Listen to your body and avoid overexertion.', 'हिंदी': 'वायरल संक्रमण के बाद थकान महसूस होना आम बात है। सुनिश्चित करें कि आप पर्याप्त आराम करें, खूब सारे तरल पदार्थ पीकर हाइड्रेटेड रहें और पौष्टिक भोजन करें। धीरे-धीरे चलने जैसी हल्की शारीरिक गतिविधि फिर से शुरू करें। अपने शरीर की सुनें और अधिक परिश्रम से बचें।', 'മലയാളം': 'വൈറൽ അണുബാധയ്ക്ക് ശേഷം ക്ഷീണം തോന്നുന്നത് സാധാരണമാണ്. ആവശ്യത്തിന് വിശ്രമം ഉറപ്പാക്കുക, ധാരാളം വെള്ളം കുടിച്ച് ജലാംശം നിലനിർത്തുക, പോഷകസമൃദ്ധമായ ഭക്ഷണം കഴിക്കുക. നടത്തം പോലുള്ള ലഘുവായ ശാരീരിക പ്രവർത്തനങ്ങൾ ക്രമേണ പുനരാരംഭിക്കുക. നിങ്ങളുടെ ശരീരം ശ്രദ്ധിക്കുകയും അമിതമായ ആയാസം ഒഴിവാക്കുകയും ചെയ്യുക.' },
    },
    {
      id: 'alert-3', type: 'Advisory', date: '2025-09-22',
      title: { English: 'Iron-Rich Foods for Your Diet', 'हिंदी': 'आपके आहार के लिए आयरन युक्त खाद्य पदार्थ', 'മലയാളം': 'നിങ്ങളുടെ ഭക്ഷണക്രമത്തിൽ ഇരുമ്പ് അടങ്ങിയ ഭക്ഷണങ്ങൾ' },
      summary: { English: 'Reminder to include iron-rich foods to manage your mild iron deficiency.', 'हिंदी': 'अपनी हल्की आयरन की कमी को प्रबंधित करने के लिए आयरन युक्त खाद्य पदार्थों को शामिल करने का अनुस्मारक।', 'മലയാളം': 'നിങ്ങളുടെ ചെറിയ ഇരുമ്പിന്റെ കുറവ് നിയന്ത്രിക്കുന്നതിന് ഇരുമ്പ് അടങ്ങിയ ഭക്ഷണങ്ങൾ ഉൾപ്പെടുത്താനുള്ള ഓർമ്മപ്പെടുത്തൽ.' },
      details: { English: 'To help with your mild iron deficiency, consider adding locally available foods like spinach (palak), lentils (dal), and chickpeas (chana) to your diet. Combining these with a source of Vitamin C, like lemon juice, can help improve iron absorption.', 'हिंदी': 'आपकी हल्की आयरन की कमी में मदद करने के लिए, अपने आहार में पालक, दाल और चना जैसे स्थानीय रूप से उपलब्ध खाद्य पदार्थों को शामिल करने पर विचार करें। इन्हें नींबू के रस जैसे विटामिन सी के स्रोत के साथ मिलाने से आयरन के अवशोषण में सुधार हो सकता है।', 'മലയാളം': 'നിങ്ങളുടെ ചെറിയ ഇരുമ്പിന്റെ കുറവ് പരിഹരിക്കാൻ, ചീര (പാലക്), പയർ (പരിപ്പ്), കടല (ചന) തുടങ്ങിയ പ്രാദേശികമായി ലഭ്യമായ ഭക്ഷണങ്ങൾ നിങ്ങളുടെ ഭക്ഷണത്തിൽ ചേർക്കുന്നത് പരിഗണിക്കുക. നാരങ്ങാനീര് പോലുള്ള വിറ്റാമിൻ സി യുടെ ഉറവിടവുമായി ഇവ സംയോജിപ്പിക്കുന്നത് ഇരുമ്പിന്റെ ആഗിരണം മെച്ചപ്പെടുത്താൻ സഹായിക്കും.' },
    },
     {
      id: 'alert-4', type: 'Advisory', date: '2025-09-20',
      title: { English: 'Flu Season Advisory', 'हिंदी': 'फ्लू सीजन एडवाइजरी', 'മലയാളം': 'ഫ്ലൂ സീസൺ മുന്നറിയിപ്പ്' },
      summary: { English: 'The flu season is approaching. Take steps to protect yourself and others.', 'हिंदी': 'फ्लू का मौसम आ रहा है। अपनी और दूसरों की सुरक्षा के लिए कदम उठाएं।', 'മലയാളം': 'ഫ്ലൂ സീസൺ അടുത്തുവരുന്നു. നിങ്ങളെയും മറ്റുള്ളവരെയും സംരക്ഷിക്കുന്നതിനുള്ള നടപടികൾ സ്വീകരിക്കുക.' },
      details: { English: 'Annual flu vaccination is the best way to prevent the flu. Practice good hand hygiene, avoid touching your face, and stay home if you are sick to prevent spreading germs.', 'हिंदी': 'वार्षिक फ्लू टीकाकरण फ्लू को रोकने का सबसे अच्छा तरीका है। अच्छी हाथ की स्वच्छता का अभ्यास करें, अपने चेहरे को छूने से बचें, और कीटाणुओं को फैलने से रोकने के लिए यदि आप बीमार हैं तो घर पर रहें।', 'മലയാളം': 'വാർഷിക ഫ്ലൂ വാക്സിനേഷൻ ഫ്ലൂ തടയാനുള്ള ഏറ്റവും നല്ല മാർഗമാണ്. നല്ല കൈ ശുചിത്വം പാലിക്കുക, മുഖം തൊടുന്നത് ഒഴിവാക്കുക, രോഗാണുക്കൾ പടരുന്നത് തടയാൻ അസുഖമുണ്ടെങ്കിൽ വീട്ടിൽ തന്നെ തുടരുക.' },
    }
  ];